/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FootballPlayer;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author munir
 */
public class UInterface extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Judul = new javax.swing.JLabel();
        Pname = new javax.swing.JLabel();
        ability = new javax.swing.JLabel();
        passing = new javax.swing.JLabel();
        defensive = new javax.swing.JLabel();
        Shooting = new javax.swing.JLabel();
        speed = new javax.swing.JLabel();
        physical = new javax.swing.JLabel();
        dribbling = new javax.swing.JLabel();
        JudulDicriminantFunction = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        namaBar = new javax.swing.JTextField();
        passingBar = new javax.swing.JTextField();
        defensiveBar = new javax.swing.JTextField();
        shootingBar = new javax.swing.JTextField();
        speedBar = new javax.swing.JTextField();
        dribblingBar = new javax.swing.JTextField();
        physicalBar = new javax.swing.JTextField();
        CFbar = new javax.swing.JTextField();
        LWFbar = new javax.swing.JTextField();
        LMFbar = new javax.swing.JTextField();
        LMF = new javax.swing.JLabel();
        LWF = new javax.swing.JLabel();
        SSbar = new javax.swing.JTextField();
        RWFbar = new javax.swing.JTextField();
        RWF = new javax.swing.JLabel();
        RMFbar = new javax.swing.JTextField();
        CMFbar = new javax.swing.JTextField();
        CMF = new javax.swing.JLabel();
        RMF = new javax.swing.JLabel();
        SS = new javax.swing.JLabel();
        AMFbar = new javax.swing.JTextField();
        DMFbar = new javax.swing.JTextField();
        DMF = new javax.swing.JLabel();
        LBbar = new javax.swing.JTextField();
        GKbar = new javax.swing.JTextField();
        GK = new javax.swing.JLabel();
        LB = new javax.swing.JLabel();
        AMF = new javax.swing.JLabel();
        CB = new javax.swing.JLabel();
        CBbar = new javax.swing.JTextField();
        RB = new javax.swing.JLabel();
        RBbar = new javax.swing.JTextField();
        PredictedPos = new javax.swing.JLabel();
        PredictedPosBar = new javax.swing.JTextField();
        Process = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Football Player Position");
        setPreferredSize(new java.awt.Dimension(490, 580));

        Judul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("Football Player Position Classification");
        Judul.setAutoscrolls(true);

        Pname.setText("Player Name ");
        Pname.setAutoscrolls(true);

        ability.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ability.setText("Ability");

        passing.setText("Passing");

        defensive.setText("Defensive");

        Shooting.setText("Shooting");

        speed.setText("Speed");

        physical.setText("Physical");

        dribbling.setText("Dribbling");

        JudulDicriminantFunction.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JudulDicriminantFunction.setText("Dicriminant Function");

        jLabel1.setText("CF");

        namaBar.setBorder(null);

        passingBar.setBorder(null);

        defensiveBar.setBorder(null);

        shootingBar.setBorder(null);

        speedBar.setBorder(null);

        dribblingBar.setBorder(null);

        physicalBar.setBorder(null);

        CFbar.setEditable(false);

        LWFbar.setEditable(false);

        LMFbar.setEditable(false);

        LMF.setText("LMF");

        LWF.setText("LWF");

        SSbar.setEditable(false);

        RWFbar.setEditable(false);

        RWF.setText("RWF");

        RMFbar.setEditable(false);

        CMFbar.setEditable(false);

        CMF.setText("CMF");

        RMF.setText("RMF");

        SS.setText("SS");

        AMFbar.setEditable(false);

        DMFbar.setEditable(false);

        DMF.setText("DMF");

        LBbar.setEditable(false);

        GKbar.setEditable(false);

        GK.setText("GK");

        LB.setText("LB");

        AMF.setText("AMF");

        CB.setText("CB");

        CBbar.setEditable(false);

        RB.setText("RB");

        RBbar.setEditable(false);

        PredictedPos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PredictedPos.setText("Predicted Position");

        PredictedPosBar.setEditable(false);

        Process.setText("Process");
        Process.setToolTipText("");
        Process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(JudulDicriminantFunction))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ability)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(defensive)
                                    .addComponent(passing))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(defensiveBar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Shooting)
                                    .addComponent(speed)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(CFbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LMF)
                                    .addGap(18, 18, 18)
                                    .addComponent(LMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LWF)
                                    .addGap(18, 18, 18)
                                    .addComponent(LWFbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(DMF)
                                    .addGap(18, 18, 18)
                                    .addComponent(DMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AMF)
                                    .addGap(18, 18, 18)
                                    .addComponent(AMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LB)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(GK)
                                    .addGap(18, 18, 18)
                                    .addComponent(GKbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(speedBar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shootingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dribbling)
                                    .addComponent(physical))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(physicalBar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                    .addComponent(dribblingBar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RWF)
                                .addGap(18, 18, 18)
                                .addComponent(RWFbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SS)
                                .addGap(18, 18, 18)
                                .addComponent(SSbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CMF)
                                .addGap(18, 18, 18)
                                .addComponent(CMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RMF)
                                .addGap(18, 18, 18)
                                .addComponent(RMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CB)
                                .addGap(18, 18, 18)
                                .addComponent(CBbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RB)
                                .addGap(18, 18, 18)
                                .addComponent(RBbar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(namaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Pname)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PredictedPos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 181, Short.MAX_VALUE)
                .addComponent(Process)
                .addGap(199, 199, 199))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PredictedPosBar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Judul)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pname)
                    .addComponent(namaBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ability)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(passing)
                                .addComponent(passingBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Shooting)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(physical)
                                .addComponent(physicalBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(defensive)
                                .addComponent(defensiveBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(speed)
                                .addComponent(speedBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dribbling)
                            .addComponent(dribblingBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(JudulDicriminantFunction))
                    .addComponent(shootingBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CFbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LWFbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LWF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LMF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AMF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DMF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RWFbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RWF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RMF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CMFbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CMF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RB))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GKbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(Process)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PredictedPos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PredictedPosBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessActionPerformed
        
        try {
            Player player = new Player();
            player.setPlayerName(namaBar.getText());
            player.setPassing(Integer.parseInt(passingBar.getText()));
            player.setShooting(Integer.parseInt(shootingBar.getText()));
            player.setPhysical(Integer.parseInt(physicalBar.getText()));
            player.setDefensive(Integer.parseInt(defensiveBar.getText()));
            player.setSpeed(Integer.parseInt(speedBar.getText()));
            player.setDribbling(Integer.parseInt(dribblingBar.getText()));
            
            player.setDiscriminant();
            
            double []position = player.getDiscriminant();
            
            for (int i = 0; i < position.length; i++) {
                position[i] = Math.floor(position[i] * 1000000) / 1000000;
            }
            
            CFbar.setText(String.valueOf(position[0]));
            SSbar.setText(String.valueOf(position[1]));
            RWFbar.setText(String.valueOf(position[2]));
            LWFbar.setText(String.valueOf(position[3]));
            AMFbar.setText(String.valueOf(position[4]));
            RMFbar.setText(String.valueOf(position[5]));
            LMFbar.setText(String.valueOf(position[6]));
            CMFbar.setText(String.valueOf(position[7]));
            DMFbar.setText(String.valueOf(position[8]));
            RBbar.setText(String.valueOf(position[9]));
            LBbar.setText(String.valueOf(position[10]));
            CBbar.setText(String.valueOf(position[11]));
            GKbar.setText(String.valueOf(position[12]));
            
            player.setPosition();
            
            PredictedPosBar.setText(player.getPlayerName()+" is "+player.getPosition());
            
            
        } catch (SQLException ex) {
            Logger.getLogger(UInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProcessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AMF;
    private javax.swing.JTextField AMFbar;
    private javax.swing.JLabel CB;
    private javax.swing.JTextField CBbar;
    private javax.swing.JTextField CFbar;
    private javax.swing.JLabel CMF;
    private javax.swing.JTextField CMFbar;
    private javax.swing.JLabel DMF;
    private javax.swing.JTextField DMFbar;
    private javax.swing.JLabel GK;
    private javax.swing.JTextField GKbar;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel JudulDicriminantFunction;
    private javax.swing.JLabel LB;
    private javax.swing.JTextField LBbar;
    private javax.swing.JLabel LMF;
    private javax.swing.JTextField LMFbar;
    private javax.swing.JLabel LWF;
    private javax.swing.JTextField LWFbar;
    private javax.swing.JLabel Pname;
    private javax.swing.JLabel PredictedPos;
    private javax.swing.JTextField PredictedPosBar;
    private javax.swing.JButton Process;
    private javax.swing.JLabel RB;
    private javax.swing.JTextField RBbar;
    private javax.swing.JLabel RMF;
    private javax.swing.JTextField RMFbar;
    private javax.swing.JLabel RWF;
    private javax.swing.JTextField RWFbar;
    private javax.swing.JLabel SS;
    private javax.swing.JTextField SSbar;
    private javax.swing.JLabel Shooting;
    private javax.swing.JLabel ability;
    private javax.swing.JLabel defensive;
    private javax.swing.JTextField defensiveBar;
    private javax.swing.JLabel dribbling;
    private javax.swing.JTextField dribblingBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField namaBar;
    private javax.swing.JLabel passing;
    private javax.swing.JTextField passingBar;
    private javax.swing.JLabel physical;
    private javax.swing.JTextField physicalBar;
    private javax.swing.JTextField shootingBar;
    private javax.swing.JLabel speed;
    private javax.swing.JTextField speedBar;
    // End of variables declaration//GEN-END:variables
}
